
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: team01-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"Ryan-HomeController","number":31,"title":"Add Home Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/31"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"Cap-Holiday-Service","number":30,"title":"Add Public Holiday Service","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/30"},{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"JosephBranch","number":29,"title":"change api location","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/29"},{"author":{"id":"MDQ6VXNlcjM3NDc5NDM3","is_bot":false,"login":"shamitagurusu","name":"Shamita Gurusu"},"headRefName":"shamita-jokes","number":28,"title":"Joke Service + Test Implementation","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/28"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"Cap-Holiday-Controller","number":27,"title":"Add Public Holiday Service and Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/27"}]
