
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: team01-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"JosephBranch","number":35,"title":"fix test","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/35"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"Ryan-University-Controller","number":33,"title":"Edit University Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/33"}]
