
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: team01-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4MTY0Njk0","is_bot":false,"login":"cydthe","name":""},"headRefName":"Cindy-Zipcode-Controller","number":26,"title":"cg - Implelement ZipCodeController Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/26"},{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"Joseph-LocationQueryService","number":25,"title":"Joseph location query service","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/25"},{"author":{"id":"MDQ6VXNlcjY4MTY0Njk0","is_bot":false,"login":"cydthe","name":""},"headRefName":"Cindy-Zipcode","number":22,"title":"Add Zipcode Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/22"},{"author":{"id":"MDQ6VXNlcjQ4Njc4MTQ1","is_bot":false,"login":"wzqd","name":"Jason Gu"},"headRefName":"Jason-Tide-Controller","number":21,"title":"Add tide controller and controller tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/21"},{"author":{"id":"MDQ6VXNlcjQ4Njc4MTQ1","is_bot":false,"login":"wzqd","name":"Jason Gu"},"headRefName":"Jason-Tide","number":20,"title":"Add Tides Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/20"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"Ryan-University-Controller","number":19,"title":"Add University Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/19"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"Ryan-University","number":18,"title":"Add University Service and Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-3/pull/18"}]
